# Generated by Django 5.2.1 on 2025-08-29 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movielens_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('imdb_id', models.CharField(blank=True, db_index=True, default='', max_length=16)),
                ('tmdb_id', models.CharField(blank=True, db_index=True, default='', max_length=16)),
                ('title', models.CharField(db_index=True, max_length=512)),
                ('year', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('genres', models.CharField(blank=True, default='', max_length=256)),
                ('description', models.TextField(blank=True, default='')),
                ('poster_url', models.URLField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
                'indexes': [models.Index(fields=['title'], name='api_movie_title_f63d7e_idx'), models.Index(fields=['year'], name='api_movie_year_4bd6e9_idx'), models.Index(fields=['genres'], name='api_movie_genres_bb9e7b_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_genres', models.CharField(blank=True, default='', max_length=256)),
                ('bio', models.TextField(blank=True, default='')),
                ('avatar_url', models.URLField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('review', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='api.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user'], name='api_rating_user_id_1b0478_idx'), models.Index(fields=['movie'], name='api_rating_movie_i_a96108_idx'), models.Index(fields=['rating'], name='api_rating_rating_7cf488_idx')],
                'unique_together': {('user', 'movie')},
            },
        ),
    ]
